name: Unity Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ runner.os }}
        restore-keys: Library-

    - name: Build project
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 6000.0.44f1
        targetPlatform: StandaloneWindows64
